"""Requirements traceability: every field named in the product brief, mapped to columns.

This is the contract between the brief and the schema. ``gen_data_dictionary.py``
verifies that every column named here actually exists, so the mapping cannot rot.
"""

from __future__ import annotations

TECHNICAL = {
    "Applicable standard": [
        "pumps.applicable_standard",
        "pumps.additional_standards",
        "pumps.standard_edition",
        "technical_specs.api_610_type_code",
        "technical_specs.standard_compliance_notes",
        "technical_specs.deviations_to_standard",
    ],
    "Pump type": ["pumps.pump_type", "pumps.pump_type_raw"],
    "Capacity and head": [
        "technical_specs.rated_capacity_m3h",
        "technical_specs.min_capacity_m3h",
        "technical_specs.max_capacity_m3h",
        "technical_specs.min_continuous_stable_flow_m3h",
        "technical_specs.bep_capacity_m3h",
        "technical_specs.rated_head_m",
        "technical_specs.max_head_m",
        "technical_specs.shutoff_head_m",
        "technical_specs.differential_pressure_barg",
    ],
    "NPSH required and efficiency": [
        "technical_specs.npsh_required_m",
        "technical_specs.npsh_available_m",
        "technical_specs.npsh_margin_m",
        "technical_specs.hydraulic_efficiency_pct",
        "technical_specs.bep_efficiency_pct",
    ],
    "Speed and driver": [
        "technical_specs.rated_speed_rpm",
        "technical_specs.min_speed_rpm",
        "technical_specs.max_speed_rpm",
        "technical_specs.is_variable_speed",
        "technical_specs.driver_type",
        "technical_specs.driver_rated_power_kw",
        "technical_specs.driver_manufacturer",
        "technical_specs.driver_voltage_v",
        "technical_specs.driver_frequency_hz",
        "technical_specs.driver_enclosure",
        "technical_specs.coupling_type",
        "technical_specs.gearbox_required",
    ],
    "Materials of construction": [
        "technical_specs.material_class",
        "technical_specs.casing_material",
        "technical_specs.impeller_material",
        "technical_specs.shaft_material",
        "technical_specs.wear_parts_material",
        "technical_specs.gasket_material",
        "technical_specs.fastener_material",
        "technical_specs.nace_mr0175_compliant",
        "technical_specs.corrosion_allowance_mm",
        "technical_specs.material_certification",
    ],
    "Seal system": [
        "technical_specs.seal_system_type",
        "technical_specs.seal_api_682_category",
        "technical_specs.seal_arrangement",
        "technical_specs.seal_piping_plan",
        "technical_specs.seal_manufacturer",
        "technical_specs.seal_face_materials",
        "technical_specs.seal_elastomer",
        "technical_specs.barrier_buffer_fluid",
    ],
    "Bearing type and lubrication": [
        "technical_specs.radial_bearing_type",
        "technical_specs.thrust_bearing_type",
        "technical_specs.bearing_arrangement",
        "technical_specs.bearing_life_hours",
        "technical_specs.lubrication_type",
        "technical_specs.lubricant_grade",
        "technical_specs.lube_oil_system_scope",
        "technical_specs.bearing_isolators",
    ],
    "Area classification": [
        "technical_specs.area_classification",
        "technical_specs.gas_group",
        "technical_specs.temperature_class",
        "technical_specs.equipment_protection_level",
        "technical_specs.ingress_protection",
        "technical_specs.atex_certified",
        "technical_specs.iecex_certified",
        "technical_specs.ex_certificate_numbers",
    ],
    "Casing design rating": [
        "technical_specs.casing_type",
        "technical_specs.casing_design_pressure_barg",
        "technical_specs.max_allowable_working_pressure_barg",
        "technical_specs.casing_design_temperature_min_c",
        "technical_specs.casing_design_temperature_max_c",
        "technical_specs.hydrostatic_test_pressure_barg",
        "technical_specs.pressure_class",
        "technical_specs.casing_design_code",
        "technical_specs.nozzle_load_capability",
    ],
    "Testing requirements": [
        "technical_specs.performance_test_required",
        "technical_specs.performance_test_grade",
        "technical_specs.npsh_test_required",
        "technical_specs.mechanical_run_test_required",
        "technical_specs.hydrostatic_test_required",
        "technical_specs.string_test_required",
        "technical_specs.complete_unit_test_required",
        "technical_specs.nde_requirements",
        "technical_specs.witness_level",
        "technical_specs.test_standard",
    ],
    "Coating / painting specification": [
        "technical_specs.external_coating_spec",
        "technical_specs.internal_coating_spec",
        "technical_specs.paint_system_standard",
        "technical_specs.coating_dft_microns",
        "technical_specs.surface_preparation",
        "technical_specs.corrosion_category",
        "technical_specs.galvanic_protection",
    ],
    "Instrumentation and controls interface": [
        "technical_specs.instrumentation_scope",
        "technical_specs.vibration_monitoring",
        "technical_specs.api_670_compliant",
        "technical_specs.temperature_monitoring",
        "technical_specs.pressure_instrumentation",
        "technical_specs.control_interface_protocol",
        "technical_specs.local_control_panel",
        "technical_specs.junction_box_certification",
        "technical_specs.condition_monitoring_ready",
        "technical_specs.signal_list",
    ],
    "Third-party / marine certification": [
        "technical_specs.marine_class_society",
        "technical_specs.marine_certification_type",
        "technical_specs.third_party_certifications",
        "technical_specs.certificate_numbers",
        "technical_specs.certification_valid_until",
        "technical_specs.inspection_authority",
    ],
    "Spares interchangeability": [
        "technical_specs.spares_interchangeable_with",
        "technical_specs.parts_commonality_pct",
        "technical_specs.common_rotating_element",
        "technical_specs.interchangeability_notes",
        "technical_specs.obsolescence_risk",
    ],
}

COMMERCIAL = {
    "Base price and terms": [
        "commercial_specs.base_price_amount",
        "commercial_specs.base_price_currency",
        "commercial_specs.base_price_usd",
        "commercial_specs.price_basis",
        "commercial_specs.price_validity_days",
        "commercial_specs.quotation_reference",
        "commercial_specs.quotation_date",
        "commercial_specs.incoterm",
        "commercial_specs.incoterm_named_place",
    ],
    "Payment terms": [
        "commercial_specs.payment_terms",
        "commercial_specs.advance_payment_pct",
        "commercial_specs.payment_days_net",
        "commercial_specs.letter_of_credit_required",
        "commercial_specs.retention_pct",
        "commercial_specs.liquidated_damages_terms",
        "commercial_specs.liquidated_damages_cap_pct",
    ],
    "Warranty": [
        "commercial_specs.warranty_months",
        "commercial_specs.warranty_basis",
        "commercial_specs.warranty_scope",
        "commercial_specs.extended_warranty_available",
        "commercial_specs.extended_warranty_cost_pct",
    ],
    "Spares pricing": [
        "commercial_specs.spares_price_amount",
        "commercial_specs.spares_price_currency",
        "commercial_specs.commissioning_spares_usd",
        "commercial_specs.two_year_spares_usd",
        "commercial_specs.capital_spares_usd",
        "commercial_specs.spares_price_list",
        "commercial_specs.spares_discount_pct",
    ],
    "Price escalation formula": [
        "commercial_specs.price_escalation_formula",
        "commercial_specs.escalation_index_reference",
        "commercial_specs.escalation_base_date",
        "commercial_specs.escalation_annual_pct",
    ],
    "Discount / volume pricing": [
        "commercial_specs.discount_pct",
        "commercial_specs.volume_discount_schedule",
        "commercial_specs.frame_agreement_reference",
    ],
    "Historical price benchmark": [
        "commercial_specs.historical_price_benchmark_usd",
        "commercial_specs.benchmark_source",
        "commercial_specs.benchmark_date",
        "commercial_specs.benchmark_variance_pct",
    ],
    "Life-cycle cost estimate": [
        "commercial_specs.lifecycle_cost_usd",
        "commercial_specs.lifecycle_period_years",
        "commercial_specs.energy_cost_per_year_usd",
        "commercial_specs.maintenance_cost_per_year_usd",
        "commercial_specs.lifecycle_assumptions",
    ],
    "Taxes, duties and local content": [
        "commercial_specs.taxes_included",
        "commercial_specs.tax_details",
        "commercial_specs.import_duty_pct",
        "commercial_specs.customs_hs_code",
        "commercial_specs.local_content_pct",
        "commercial_specs.local_content_scheme",
        "commercial_specs.local_content_certificate",
        "commercial_specs.withholding_tax_pct",
    ],
    "Financial standing": [
        "vendors.annual_revenue_usd",
        "vendors.revenue_year",
        "vendors.employee_count",
        "vendors.credit_rating",
        "vendors.credit_rating_agency",
        "vendors.dun_bradstreet_number",
        "vendors.financial_standing_notes",
        "commercial_specs.financial_standing_summary",
        "commercial_specs.parent_company_guarantee_available",
    ],
    "Bonding and insurance capability": [
        "vendors.bonding_capacity_usd",
        "vendors.can_provide_performance_bond",
        "vendors.can_provide_advance_payment_guarantee",
        "vendors.insurance_coverage_usd",
        "vendors.insurance_details",
        "commercial_specs.bonding_capability",
        "commercial_specs.insurance_capability",
    ],
}

DIMENSIONAL = {
    "Dry weight": [
        "dimensional_specs.dry_weight_kg",
        "dimensional_specs.pump_only_weight_kg",
        "dimensional_specs.driver_weight_kg",
        "dimensional_specs.baseplate_weight_kg",
    ],
    "Operating weight": ["dimensional_specs.operating_weight_kg"],
    "Shipping weight and crate dimensions": [
        "dimensional_specs.shipping_weight_kg",
        "dimensional_specs.crate_length_mm",
        "dimensional_specs.crate_width_mm",
        "dimensional_specs.crate_height_mm",
        "dimensional_specs.crate_volume_m3",
        "dimensional_specs.number_of_packages",
    ],
    "Footprint / baseplate dimensions": [
        "dimensional_specs.baseplate_length_mm",
        "dimensional_specs.baseplate_width_mm",
        "dimensional_specs.baseplate_height_mm",
        "dimensional_specs.baseplate_type",
        "dimensional_specs.footprint_area_m2",
        "dimensional_specs.overall_length_mm",
        "dimensional_specs.overall_width_mm",
        "dimensional_specs.overall_height_mm",
        "dimensional_specs.maintenance_access_envelope_mm",
    ],
    "Centre of gravity and lifting points": [
        "dimensional_specs.cog_x_mm",
        "dimensional_specs.cog_y_mm",
        "dimensional_specs.cog_z_mm",
        "dimensional_specs.cog_reference_datum",
        "dimensional_specs.lifting_points_count",
        "dimensional_specs.lifting_point_details",
        "dimensional_specs.lifting_arrangement_standard",
        "dimensional_specs.certified_lifting_set_included",
    ],
    "Foundation loading requirements": [
        "dimensional_specs.static_load_kn",
        "dimensional_specs.dynamic_load_kn",
        "dimensional_specs.torque_reaction_knm",
        "dimensional_specs.anchor_bolt_count",
        "dimensional_specs.anchor_bolt_size",
        "dimensional_specs.foundation_loading_notes",
        "dimensional_specs.grouting_requirement",
        "dimensional_specs.vibration_isolation_required",
    ],
    "Maximum maintenance lift weight": [
        "dimensional_specs.max_maintenance_lift_weight_kg",
        "dimensional_specs.max_maintenance_lift_item",
    ],
    "Packaging type": [
        "dimensional_specs.packaging_type",
        "dimensional_specs.packaging_standard",
        "dimensional_specs.preservation_period_months",
    ],
    "FPSO topside module space envelope": [
        "dimensional_specs.fpso_module_space_envelope",
        "dimensional_specs.fpso_module_envelope_length_mm",
        "dimensional_specs.fpso_module_envelope_width_mm",
        "dimensional_specs.fpso_module_envelope_height_mm",
        "dimensional_specs.deck_area_required_m2",
        "dimensional_specs.module_integration_notes",
        "dimensional_specs.motion_design_criteria",
    ],
}

DELIVERY = {
    "Standard lead time": [
        "delivery_specs.standard_lead_time_weeks",
        "delivery_specs.lead_time_basis",
        "delivery_specs.engineering_lead_time_weeks",
        "delivery_specs.manufacturing_lead_time_weeks",
    ],
    "Expedited lead time and premium": [
        "delivery_specs.expedited_lead_time_weeks",
        "delivery_specs.expedite_premium_pct",
        "delivery_specs.expedite_premium_usd",
        "delivery_specs.expedite_conditions",
    ],
    "Manufacturing locations": [
        "delivery_specs.manufacturing_locations",
        "delivery_specs.primary_manufacturing_country",
        "delivery_specs.assembly_location",
        "delivery_specs.testing_location",
        "delivery_specs.workshop_capacity_notes",
        "delivery_specs.current_backlog_weeks",
        "vendors.manufacturing_countries",
    ],
    "Logistics / shipping lead time": [
        "delivery_specs.logistics_lead_time_weeks",
        "delivery_specs.shipping_mode",
        "delivery_specs.port_of_loading",
        "delivery_specs.freight_cost_estimate_usd",
        "delivery_specs.oversize_cargo",
        "delivery_specs.logistics_notes",
    ],
    "Incoterms offered": [
        "delivery_specs.incoterms_offered",
        "delivery_specs.preferred_incoterm",
    ],
    "Documentation lead time": [
        "delivery_specs.documentation_lead_time_weeks",
        "delivery_specs.final_documentation_weeks_after_delivery",
        "delivery_specs.document_deliverables_list",
        "delivery_specs.documentation_language",
        "delivery_specs.as_built_documentation_included",
    ],
    "FAT scheduling and duration": [
        "delivery_specs.fat_lead_time_weeks",
        "delivery_specs.fat_duration_days",
        "delivery_specs.fat_notice_period_weeks",
        "delivery_specs.fat_location",
        "delivery_specs.fat_witness_slots",
        "delivery_specs.sat_supported",
        "delivery_specs.fat_scheduling_notes",
    ],
    "Historical on-time delivery %": [
        "delivery_specs.historical_on_time_delivery_pct",
        "delivery_specs.otd_sample_size",
        "delivery_specs.otd_measurement_period",
        "delivery_specs.average_delay_weeks",
        "delivery_specs.delivery_risk_notes",
        "vendors.on_time_delivery_pct",
    ],
    "Long-lead sub-component dependencies": [
        "delivery_specs.long_lead_components",
        "delivery_specs.critical_subsupplier_dependencies",
        "delivery_specs.single_source_components",
        "delivery_specs.forging_casting_lead_time_weeks",
    ],
    "Country of origin / export control": [
        "delivery_specs.country_of_origin",
        "delivery_specs.export_control_classification",
        "delivery_specs.export_licence_required",
        "delivery_specs.export_licence_lead_time_weeks",
        "delivery_specs.restricted_destinations",
        "delivery_specs.us_content_pct",
        "delivery_specs.export_control_notes",
    ],
}

OPERATIONAL = {
    "Reference list": [
        "operational_specs.reference_list",
        "operational_specs.reference_count",
        "operational_specs.reference_contactable",
    ],
    "Units supplied / installed": [
        "operational_specs.units_supplied",
        "operational_specs.units_installed_operating",
        "operational_specs.first_installation_year",
        "operational_specs.cumulative_operating_hours",
        "vendors.total_units_supplied",
    ],
    "Reliability data": [
        "operational_specs.mtbf_hours",
        "operational_specs.mttr_hours",
        "operational_specs.availability_pct",
        "operational_specs.failure_rate_per_year",
        "operational_specs.common_failure_modes",
        "operational_specs.reliability_data_source",
        "operational_specs.seal_mtbf_hours",
        "operational_specs.overhaul_interval_hours",
    ],
    "FPSO / offshore experience": [
        "operational_specs.fpso_experience",
        "operational_specs.fpso_units_supplied",
        "operational_specs.fpso_project_references",
        "operational_specs.offshore_experience_years",
        "operational_specs.harsh_environment_experience",
        "operational_specs.subsea_experience",
        "vendors.fpso_offshore_experience",
    ],
    "After-sales service network": [
        "operational_specs.service_network_countries",
        "operational_specs.service_centers",
        "operational_specs.nearest_service_center",
        "operational_specs.response_time_hours",
        "operational_specs.field_service_engineers_count",
        "operational_specs.service_agreement_options",
        "operational_specs.remote_monitoring_offered",
    ],
    "Post-warranty spares availability": [
        "operational_specs.post_warranty_spares_years",
        "operational_specs.spares_availability_commitment",
        "operational_specs.spares_stock_locations",
        "operational_specs.typical_spares_delivery_weeks",
        "operational_specs.obsolescence_management_policy",
    ],
    "Training and commissioning support": [
        "operational_specs.training_offered",
        "operational_specs.training_scope",
        "operational_specs.training_days_included",
        "operational_specs.commissioning_support_included",
        "operational_specs.commissioning_support_days",
        "operational_specs.supervision_day_rate_usd",
        "operational_specs.documentation_training_language",
    ],
    "HSE performance and incident history": [
        "operational_specs.hse_trir",
        "operational_specs.hse_ltifr",
        "operational_specs.hse_fatalities_last_5y",
        "operational_specs.hse_incident_history",
        "operational_specs.hse_management_system",
        "operational_specs.hse_audit_date",
    ],
    "QA/QC certifications": [
        "operational_specs.qaqc_certifications",
        "operational_specs.quality_certificate_expiry",
        "operational_specs.itp_available",
        "operational_specs.audit_history",
        "operational_specs.ncr_history_notes",
    ],
    "Vendor approval status": [
        "vendors.approval_status",
        "vendors.approval_expiry",
        "vendors.approved_by_user_id",
        "operational_specs.vendor_approval_notes",
        "operational_specs.approved_vendor_list_membership",
    ],
    "Vendor tier / category": ["vendors.vendor_tier", "vendors.vendor_category"],
    "Sanctions / geopolitical screening status": [
        "vendors.sanctions_status",
        "vendors.sanctions_screened_at",
        "vendors.sanctions_notes",
        "vendors.geopolitical_risk_notes",
    ],
}

ADMINISTRATIVE = {
    "Legal entity and registration details": [
        "administrative_specs.legal_entity_name",
        "administrative_specs.legal_form",
        "administrative_specs.registration_number",
        "administrative_specs.registration_country",
        "administrative_specs.registration_authority",
        "administrative_specs.tax_identification_number",
        "administrative_specs.vat_number",
        "administrative_specs.lei_code",
        "administrative_specs.registered_address",
        "administrative_specs.incorporation_date",
        "administrative_specs.ultimate_parent_company",
        "administrative_specs.ownership_structure",
        "administrative_specs.beneficial_ownership_disclosed",
    ],
    "Authorized representative / agent": [
        "administrative_specs.authorized_representative_name",
        "administrative_specs.authorized_representative_title",
        "administrative_specs.authorized_representative_email",
        "administrative_specs.authorized_representative_phone",
        "administrative_specs.local_agent_name",
        "administrative_specs.local_agent_country",
        "administrative_specs.agency_agreement_reference",
        "administrative_specs.agency_agreement_expiry",
        "administrative_specs.power_of_attorney_on_file",
        "vendor_contacts.contact_role",
        "vendor_contacts.company_name",
        "vendor_contacts.territory",
        "vendor_contacts.agency_agreement_valid_until",
    ],
    "ESG / sustainability disclosures": [
        "administrative_specs.esg_report_published",
        "administrative_specs.esg_report_url",
        "administrative_specs.esg_rating_provider",
        "administrative_specs.esg_rating",
        "administrative_specs.scope1_emissions_tco2e",
        "administrative_specs.scope2_emissions_tco2e",
        "administrative_specs.scope3_emissions_reported",
        "administrative_specs.net_zero_target_year",
        "administrative_specs.iso_14001_certified",
        "administrative_specs.iso_50001_certified",
        "administrative_specs.modern_slavery_statement",
        "administrative_specs.anti_bribery_policy",
        "administrative_specs.conflict_minerals_policy",
        "administrative_specs.diversity_disclosures",
    ],
    "Cybersecurity posture": [
        "administrative_specs.iso_27001_certified",
        "administrative_specs.iec_62443_compliance",
        "administrative_specs.soc2_report_available",
        "administrative_specs.penetration_test_frequency",
        "administrative_specs.security_incident_history",
        "administrative_specs.supply_chain_security_program",
        "administrative_specs.remote_access_policy",
        "administrative_specs.cyber_insurance",
        "administrative_specs.cybersecurity_questionnaire_completed",
    ],
    "Data submission date and source": [
        "administrative_specs.data_submission_date",
        "administrative_specs.submitted_by_name",
        "administrative_specs.submitted_by_organisation",
        "administrative_specs.submission_channel",
        "administrative_specs.source_reference",
        "administrative_specs.data_owner",
        "sources.source_type",
        "sources.source_url",
        "sources.captured_at",
        "sources.content_hash",
        "field_provenance.source_id",
        "field_provenance.evidence_quote",
        "field_provenance.evidence_locator",
    ],
    "Data confidence / verification level": [
        "vendors.confidence_level",
        "vendors.verification_status",
        "pump_models.confidence_level",
        "pump_models.verification_status",
        "technical_specs.confidence_level",
        "technical_specs.verification_status",
        "administrative_specs.verification_method",
        "administrative_specs.verified_by_user_id",
        "administrative_specs.verified_at",
        "administrative_specs.completeness_pct",
        "field_provenance.confidence_level",
        "field_provenance.confidence_score",
        "confidence_scores.score",
        "data_quality_flags.flag_type",
    ],
}

REQUIREMENTS: dict[str, dict[str, list[str]]] = {
    "Technical data": TECHNICAL,
    "Commercial data": COMMERCIAL,
    "Weight and dimensional data": DIMENSIONAL,
    "Delivery data": DELIVERY,
    "Operational and track record data": OPERATIONAL,
    "Administrative and data-quality data": ADMINISTRATIVE,
}


def all_referenced_columns() -> list[str]:
    return sorted(
        {
            column
            for group in REQUIREMENTS.values()
            for columns in group.values()
            for column in columns
        }
    )
